Output demo-play.mp4

Set Shell fish
Set FontFamily "Fira Code"
Set FontSize 20
# Set LetterSpacing 20
Set Width 1920
Set Height 1080
# Set LineHeight 1.8
Set TypingSpeed 100ms
Set CursorBlink false

Type "dotnet run"
Enter
Sleep 2s
Type "5"
Enter
Enter
Sleep 500ms
Type "p"
Enter

# mvoes beginn here
Type "1"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "3"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "3"
Enter
Type "2"
Enter
Type "1"
Enter
Type "2"
Enter
Type "3"
Enter
Type "1"
Enter
Type "3"
Enter

Sleep 3s
